apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-flask
  template:
    metadata:
      labels:
        app: demo-flask
    spec:
      containers:
      - name: flask
        image: demo-flask-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-flask-service
spec:
  type: NodePort
  selector:
    app: demo-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
